# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    jdkVersion: 1.11
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'
  env:
    API_WEATHER_FORECAST_RELEASE: $(API_WEATHER_FORECAST_RELEASE)

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    jdkVersion: 1.11
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'testRelease'
    
- task: AndroidSigning@2
  inputs:
    apkFiles: '**/*.apk'
    jarsign: true
    jarsignerKeystoreFile: 'release.keystore'
    jarsignerKeystorePassword: '$(jarsignerKeystorePassword)'
    jarsignerKeystoreAlias: 'key0'
    jarsignerKeyPassword: '$(jarsignerKeyPassword)'
    zipalign: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      ls
      cd ..

- task: AppCenterTest@1
  inputs:
    #appFile: '../app/release/app-release.apk'
    appFile: '**/app-release.apk'
    artifactsDirectory: '$(Build.ArtifactStagingDirectory)/AppCenterTest'
    prepareTests: false
    runTests: false

#task that deploys on appcenter. Needs a service connection with appcenter using APPCENTER_APITOKEN_SRVUSR-PRO
- task: AppCenterDistribute@3
  displayName: 'Deploy Appcenter'
  inputs:
    serverEndpoint: '339096becf8dc2d3c779314d55701db561045bc3'
    appSlug: '$(app_slug)'
    appFile: '**/app-release.apk'
    symbolsOption: 'Android'
    #symbolsMappingTxtFile: '$(mapping_route)'
    releaseNotesOption: 'input'
    releaseNotesInput: '**'
    destinationType: 'groups'