# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    jdkVersion: 1.11
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'
  env:
    API_WEATHER_FORECAST_RELEASE: $(API_WEATHER_FORECAST_RELEASE)

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: true
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    jdkVersion: 1.11
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'testRelease'
    
- task: AndroidSigning@2
  inputs:
    apkFiles: '**/*.apk'
    jarsign: true
    jarsignerKeystoreFile: '../keystore/release.keystore'
    jarsignerKeystorePassword: '$(jarsignerKeystorePassword)'
    jarsignerKeystoreAlias: 'key0'
    jarsignerKeyPassword: '$(jarsignerKeyPassword)'
    zipalign: true