# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      export API_TEST=$(API_TEST)
      echo "##vso[task.setvariable variable=API_TEST]$(API_TEST)"
      env
      #launchctl setenv API_TEST $(API_TEST)
      #launchctl setenv "API_TEST" "$(API_TEST)">
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    jdkVersion: 1.11
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'printVar'
    #tasks: 'assembleDebug'
    
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      env